updated jenkinsfile

diff --git a/Jenkinsfile-ec2-cluster-destroy b/Jenkinsfile-ec2-cluster-destroy
--- a/Jenkinsfile-ec2-cluster-destroy
+++ b/Jenkinsfile-ec2-cluster-destroy
@@ -10,10 +10,9 @@ pipeline {
         stage('Start Alpine Container') {
             steps {
                 echo "Starting temporary Alpine container..."
-                // Run container in detached mode and mount workspace
                 sh '''
-                    docker rm -f jenkins-build || true
-                    docker run -d --name jenkins-build \
+                    docker rm -f jenkins-destroy || true
+                    docker run -d --name jenkins-destroy \
                         -v $PWD:/workspace \
                         -w /workspace \
                         alpine:3.19 tail -f /dev/null
@@ -24,14 +23,14 @@ pipeline {
         stage('Install Dependencies') {
             steps {
                 sh '''
-                docker exec jenkins-build sh -c "
-                    apk add --no-cache git bash curl unzip &&
-                    cd /tmp &&
-                    curl -LO https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip &&
-                    unzip -o terraform_1.6.6_linux_amd64.zip &&
-                    mv terraform /usr/local/bin/ &&
-                    terraform version
-                "
+                    docker exec jenkins-destroy sh -c "
+                        apk add --no-cache git bash curl unzip &&
+                        cd /tmp &&
+                        curl -LO https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip &&
+                        unzip -o terraform_1.6.6_linux_amd64.zip &&
+                        mv terraform /usr/local/bin/ &&
+                        terraform version
+                    "
                 '''
             }
         }
@@ -48,43 +47,17 @@ pipeline {
                 withCredentials([
                     string(credentialsId: 'AWS_ACCESS_KEY_ID', variable: 'AWS_ACCESS_KEY_ID'),
                     string(credentialsId: 'AWS_SECRET_ACCESS_KEY', variable: 'AWS_SECRET_ACCESS_KEY'),
-                    string(credentialsId: 'JENKINS_SERVER_SSH_PUBLIC_KEY', variable: 'PUBLIC_KEY'),
-                    string(credentialsId: 'JENKINS_SERVER_SSH_PRIVATE_KEY', variable: 'PRIVATE_KEY')
+                    string(credentialsId: 'JENKINS_SERVER_SSH_PUBLIC_KEY', variable: 'JENKINS_SERVER_SSH_PUBLIC_KEY')
                 ]) {
                     sh '''
                         docker exec \
                         -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
                         -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
-                        jenkins-build sh -c "
+                        -e JENKINS_SERVER_SSH_PUBLIC_KEY="$JENKINS_SERVER_SSH_PUBLIC_KEY" \
+                        jenkins-destroy sh -c "
                             cd terraform/03-ecommerce-cluster &&
-                            terraform init \
-                                -var 'public_key_content=${PUBLIC_KEY}' \
-                                -var 'private_key_content=${PRIVATE_KEY}'
+                            terraform init -var 'jenkins_public_key=$JENKINS_SERVER_SSH_PUBLIC_KEY'
                         "
-                    '''
-                }
-            }
-        }
-
-        
-        stage('Terraform Plan') {
-            steps {
-                withCredentials([
-                    string(credentialsId: 'AWS_ACCESS_KEY_ID', variable: 'AWS_ACCESS_KEY_ID'),
-                    string(credentialsId: 'AWS_SECRET_ACCESS_KEY', variable: 'AWS_SECRET_ACCESS_KEY'),
-                    string(credentialsId: 'JENKINS_SERVER_SSH_PUBLIC_KEY', variable: 'PUBLIC_KEY'),
-                    string(credentialsId: 'JENKINS_SERVER_SSH_PRIVATE_KEY', variable: 'PRIVATE_KEY')
-                ]) {
-                    sh '''
-                        docker exec  \
-                            -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
-                            -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
-                            jenkins-build sh -c "
-                                cd terraform/03-ecommerce-cluster &&
-                                terraform plan -out=tfplan \
-                                    -var 'public_key_content=${PUBLIC_KEY}' \
-                                    -var 'private_key_content=${PRIVATE_KEY}'
-                            "
                     '''
                 }
             }
@@ -95,40 +68,18 @@ pipeline {
                 withCredentials([
                     string(credentialsId: 'AWS_ACCESS_KEY_ID', variable: 'AWS_ACCESS_KEY_ID'),
                     string(credentialsId: 'AWS_SECRET_ACCESS_KEY', variable: 'AWS_SECRET_ACCESS_KEY'),
-                    string(credentialsId: 'JENKINS_SERVER_SSH_PUBLIC_KEY', variable: 'PUBLIC_KEY'),
-                    string(credentialsId: 'JENKINS_SERVER_SSH_PRIVATE_KEY', variable: 'PRIVATE_KEY')
+                    string(credentialsId: 'JENKINS_SERVER_SSH_PUBLIC_KEY', variable: 'JENKINS_SERVER_SSH_PUBLIC_KEY')
                 ]) {
                     sh '''
                         docker exec \
                         -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
                         -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
-                        jenkins-build sh -c "
+                        -e JENKINS_SERVER_SSH_PUBLIC_KEY="$JENKINS_SERVER_SSH_PUBLIC_KEY" \
+                        jenkins-destroy sh -c "
                             cd terraform/03-ecommerce-cluster &&
-                            terraform plan -destroy -out=tfplan &&
-                            terraform apply -auto-approve tfplan\
-                                -var 'public_key_content=${PUBLIC_KEY}' \
-                                -var 'private_key_content=${PRIVATE_KEY}'
+                            terraform destroy -auto-approve -var 'jenkins_public_key=$JENKINS_SERVER_SSH_PUBLIC_KEY'
                         "
                     '''
-                }
-            }
-        }
-
-        stage('Show Terraform Outputs') {
-            steps {
-                withCredentials([
-                    string(credentialsId: 'AWS_ACCESS_KEY_ID', variable: 'AWS_ACCESS_KEY_ID'),
-                    string(credentialsId: 'AWS_SECRET_ACCESS_KEY', variable: 'AWS_SECRET_ACCESS_KEY')
-                ]) {
-                    sh """
-                        docker exec \
-                        -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
-                        -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
-                        jenkins-build sh -c '
-                            cd terraform/03-ecommerce-cluster &&
-                            terraform output
-                        '
-                    """
                 }
             }
         }
@@ -137,8 +88,8 @@ pipeline {
             steps {
                 echo "Stopping and removing temporary container..."
                 sh '''
-                    docker stop jenkins-build
-                    docker rm jenkins-build
+                    docker stop jenkins-destroy
+                    docker rm jenkins-destroy
                 '''
             }
         }
@@ -149,10 +100,10 @@ pipeline {
             cleanWs()
         }
         success {
-            echo "Terraform applied successfully!"
+            echo "Terraform infrastructure destroyed successfully!"
         }
         failure {
-            echo "Terraform run failed!"
+            echo "Failed to destroy Terraform infrastructure!"
         }
     }
 }
