updated jenkinsfile

diff --git a/Jenkinsfile-ec2-cluster-destroy b/Jenkinsfile-ec2-cluster-destroy
--- a/Jenkinsfile-ec2-cluster-destroy
+++ b/Jenkinsfile-ec2-cluster-destroy
@@ -5,12 +5,36 @@ pipeline {
         AWS_ACCESS_KEY_ID     = credentials('AWS_ACCESS_KEY_ID')
         AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
     }
-    
-    options {
-        skipDefaultCheckout()
-    }
 
     stages {
+        stage('Start Alpine Container') {
+            steps {
+                echo "Starting temporary Alpine container..."
+                // Run container in detached mode and mount workspace
+                sh '''
+                    docker rm -f jenkins-build || true
+                    docker run -d --name jenkins-build \
+                        -v $PWD:/workspace \
+                        -w /workspace \
+                        alpine:3.19 tail -f /dev/null
+                '''
+            }
+        }
+
+        stage('Install Dependencies') {
+            steps {
+                sh '''
+                docker exec jenkins-build sh -c "
+                    apk add --no-cache git bash curl unzip &&
+                    cd /tmp &&
+                    curl -LO https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip &&
+                    unzip -o terraform_1.6.6_linux_amd64.zip &&
+                    mv terraform /usr/local/bin/ &&
+                    terraform version
+                "
+                '''
+            }
+        }
 
         stage('Checkout') {
             steps {
@@ -18,52 +42,117 @@ pipeline {
                 checkout scm
             }
         }
-        stage('Debug Repo Path') {
-            steps {
-                echo "Printing current working directory and file tree..."
-                sh "pwd"
-                sh "ls -R"
-            }
-        }
+
         stage('Terraform Init') {
             steps {
-                dir('terraform/03-ecommerce-cluster') {
-                    echo "Initializing Terraform..."
-                    sh "ls"
-                    sh "pwd"
-                    sh "terraform init"
+                withCredentials([
+                    string(credentialsId: 'AWS_ACCESS_KEY_ID', variable: 'AWS_ACCESS_KEY_ID'),
+                    string(credentialsId: 'AWS_SECRET_ACCESS_KEY', variable: 'AWS_SECRET_ACCESS_KEY'),
+                    string(credentialsId: 'JENKINS_SERVER_SSH_PUBLIC_KEY', variable: 'PUBLIC_KEY'),
+                    string(credentialsId: 'JENKINS_SERVER_SSH_PRIVATE_KEY', variable: 'PRIVATE_KEY')
+                ]) {
+                    sh '''
+                        docker exec \
+                        -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
+                        -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
+                        jenkins-build sh -c "
+                            cd terraform/03-ecommerce-cluster &&
+                            terraform init \
+                                -var 'public_key_content=${PUBLIC_KEY}' \
+                                -var 'private_key_content=${PRIVATE_KEY}'
+                        "
+                    '''
                 }
             }
         }
 
-        stage('Terraform Destroy Plan') {
+        
+        stage('Terraform Plan') {
             steps {
-                dir('terraform/03-ecommerce-cluster') {
-                    echo "Planning Terraform destroy..."
-                    sh "terraform plan -destroy -out=tfdestroyplan"
+                withCredentials([
+                    string(credentialsId: 'AWS_ACCESS_KEY_ID', variable: 'AWS_ACCESS_KEY_ID'),
+                    string(credentialsId: 'AWS_SECRET_ACCESS_KEY', variable: 'AWS_SECRET_ACCESS_KEY'),
+                    string(credentialsId: 'JENKINS_SERVER_SSH_PUBLIC_KEY', variable: 'PUBLIC_KEY'),
+                    string(credentialsId: 'JENKINS_SERVER_SSH_PRIVATE_KEY', variable: 'PRIVATE_KEY')
+                ]) {
+                    sh '''
+                        docker exec  \
+                            -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
+                            -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
+                            jenkins-build sh -c "
+                                cd terraform/03-ecommerce-cluster &&
+                                terraform plan -out=tfplan \
+                                    -var 'public_key_content=${PUBLIC_KEY}' \
+                                    -var 'private_key_content=${PRIVATE_KEY}'
+                            "
+                    '''
                 }
             }
         }
 
-        stage('Terraform Destroy Apply') {
+        stage('Terraform Destroy') {
             steps {
-                dir('terraform/03-ecommerce-cluster') {
-                    echo "Destroying Terraform infrastructure..."
-                    sh "terraform apply -auto-approve tfdestroyplan"
+                withCredentials([
+                    string(credentialsId: 'AWS_ACCESS_KEY_ID', variable: 'AWS_ACCESS_KEY_ID'),
+                    string(credentialsId: 'AWS_SECRET_ACCESS_KEY', variable: 'AWS_SECRET_ACCESS_KEY'),
+                    string(credentialsId: 'JENKINS_SERVER_SSH_PUBLIC_KEY', variable: 'PUBLIC_KEY'),
+                    string(credentialsId: 'JENKINS_SERVER_SSH_PRIVATE_KEY', variable: 'PRIVATE_KEY')
+                ]) {
+                    sh '''
+                        docker exec \
+                        -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
+                        -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
+                        jenkins-build sh -c "
+                            cd terraform/03-ecommerce-cluster &&
+                            terraform plan -destroy -out=tfplan &&
+                            terraform apply -auto-approve tfplan\
+                                -var 'public_key_content=${PUBLIC_KEY}' \
+                                -var 'private_key_content=${PRIVATE_KEY}'
+                        "
+                    '''
                 }
+            }
+        }
+
+        stage('Show Terraform Outputs') {
+            steps {
+                withCredentials([
+                    string(credentialsId: 'AWS_ACCESS_KEY_ID', variable: 'AWS_ACCESS_KEY_ID'),
+                    string(credentialsId: 'AWS_SECRET_ACCESS_KEY', variable: 'AWS_SECRET_ACCESS_KEY')
+                ]) {
+                    sh """
+                        docker exec \
+                        -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
+                        -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
+                        jenkins-build sh -c '
+                            cd terraform/03-ecommerce-cluster &&
+                            terraform output
+                        '
+                    """
+                }
+            }
+        }
+
+        stage('Cleanup Container') {
+            steps {
+                echo "Stopping and removing temporary container..."
+                sh '''
+                    docker stop jenkins-build
+                    docker rm jenkins-build
+                '''
             }
         }
     }
 
     post {
-        success {
-            echo "Terraform infrastructure destroyed successfully!"
-        }
-        failure {
-            echo "Terraform destroy failed!"
-        }
         always {
-            echo "Cleaning up workspace..."
             cleanWs()
         }
+        success {
+            echo "Terraform applied successfully!"
+        }
+        failure {
+            echo "Terraform run failed!"
+        }
     }
+}
